<html>
    <head>
        <meta charset="utf-8"/>
        <title>Freeman Contingent</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 5%;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }            
	    p {
                text-align: left;
                font-weight:1;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                color: black;	    
	    }
	    
        </style>
    </head>
    <body>        
        <h2>JSON output</h2>
        <p><?php print_r($json_output); ?></p>
    </body>
</html>
